### PR TITLE
change codeSystem to use inactive as well as deprecated

### LINKED ISSUE #23: concept-property#inactive
should we add the concept-property#inactive to the deprecated codes?

I am not sure what is best-practice. I have asked HL7
https://jira.hl7.org/browse/FHIR-42956

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #23 
and cleanup new build warnings

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
https://build.fhir.org/ig/IHE/FormatCode/branches/moehrke-inactive/index.html

**Comment by JohnMoehrke** [comment]
expansion doesn't include IHE codes. Removing inactive doesn't help. So this doesn't seem related. Grahame is looking at it.

**Review by JohnMoehrke — COMMENTED** [review]
- add provenance of valueSet change
- remove commented out experiment in codeSystem

**Review by JohnMoehrke — COMMENTED** [review]
- add provenance of valueSet change
- remove commented out experiment in codeSystem
- add release json

**Comment by JohnMoehrke** [comment]
would trigger a publication of a patch release level.

**Review by lukeaduncan — APPROVED** [review]
Looks good.

**Review by oliveregger — APPROVED** [review]

**Review by lukeaduncan — APPROVED** [review]
Looks good.

**Pull request merged**
