### PR TITLE
add hierarchy definition

### LINKED ISSUE #15: codesystems now should have hierarchyMeaning
New informative message from the IG builder
CodeSystems SHOULD have a stated value for the hierarchyMeaning element so that users know the status and meaning of the code system clearly.

### PR DESCRIPTION
**Pull request by JohnMoehrke**
Given that the codes are grouped by the domain that defined them, this seems closest to the grouped-by concept.
close #15

### CODE REVIEW

**Review by ElliotSilver — COMMENTED** [review]
Looks like a reasonable change, but its getting into fancier use of code systems than I've done.

**Comment by JohnMoehrke** [comment]
To Reviewers:  I have created a rule on this github repo that two others need to review pull-requests.. figuring the changes would be because new codes were added by some domain, and thus wanting the domain co-chairs to agree... Well, now that I have a github rule, I need to live by it with even simple fixes...   So, please review to the best of your skills.

**Review by oliveregger — APPROVED** [review]

**Comment by JohnMoehrke** [comment]
> Looks like a reasonable change, but its getting into fancier use of code systems than I've done.

@ElliotSilver please approve if you are okay with the change

**Review by ElliotSilver — APPROVED** [review]

**Review by jlamy — COMMENTED** [review]
Looks good to me.

**Pull request merged**
