### PR TITLE
use the new hl7 codesystem id

### LINKED ISSUE #21: the HL7 codeSystem moved
The ValueSet tries to pull in the HL7 codes, and succeeds somehow.

But the formal codeSystem available from HL7 is now at

http://terminology.hl7.org/CodeSystem/v3-HL7DocumentFormatCodes

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #21

### CODE REVIEW

**Review by lukeaduncan — APPROVED** [review]
Looks good to me.

**Comment by JohnMoehrke** [comment]
more fixes to narrative and codeSystem for hl7 URI

**Comment by JohnMoehrke** [comment]
close #20 
close #19 
close #19

**Comment by JohnMoehrke** [comment]
http://build.fhir.org/ig/IHE/FormatCode/branches/moehrke-hl7-codesystem/index.html

**Review by slagesse-epic — APPROVED** [review]
Looks good to me.

**Pull request merged**
