### PR TITLE
add sIPS formatcode #27

### PR DESCRIPTION
**Pull request by oliveregger**
## 📑 Description
see issue #27 

## ✅ Checks
- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed
- [ x] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
It does seem to add it to the valueSet. 

I am unclear why this works, yet the dicom one does not. I figured that since the dicom code isn't added, then this wouldn't either.

**Comment by JohnMoehrke** [comment]
I am hesitant to include this in the FormatCode vocabulary as that locks it in and would require vocabulary lifecycle management if we change our mind on what to use in sIPS. Meaning, I would prefer to see implementers feedback. When this is only in the TI version of sIPS, it is far easier to change.

@oliveregger what do you think of that concern?

**Comment by JohnMoehrke** [comment]
the reason the dicom does not get added is because the validator does find the dicom system, and it then does not find this code in there. There are two warnings ignored about this. So that explains dicom code is differently handled.

**Comment by oliveregger** [comment]
The origin of the PR is from implementers who would like to have for connectathon testing a FHIR ValueSet with all the document types in use for testing at the IHE connectathon floor. Given that IHE.formatcode says:  For use with Document Sharing (XDS, XCA, MHD, etc) I would have hoped this is the method where I get all related codes relevant. I see you point that two definitions are not good, however if each IG defines its own formatCode and we have not aggregated it somewhere, nobody will find them.

**Review by JohnMoehrke — APPROVED** [review]
ok

**Pull request merged**
